// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaevHLMDESXiMmY7kpOy0PzTOj-pde_5w',
    appId: '1:767296020733:web:03763c4e63baf00c0fde94',
    messagingSenderId: '767296020733',
    projectId: 'ncc-finance-mobile',
    authDomain: 'ncc-finance-mobile.firebaseapp.com',
    storageBucket: 'ncc-finance-mobile.firebasestorage.app',
    measurementId: 'G-CSHZM3HVHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnr9MjLxHQ3TL1WsPuE19rqkRthbhd8bk',
    appId: '1:767296020733:android:50187e1044e61e390fde94',
    messagingSenderId: '767296020733',
    projectId: 'ncc-finance-mobile',
    storageBucket: 'ncc-finance-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgJpc_WopHtThpMRMvIBBrY2crQ2KfPz4',
    appId: '1:767296020733:ios:b3c6228a51a20e770fde94',
    messagingSenderId: '767296020733',
    projectId: 'ncc-finance-mobile',
    storageBucket: 'ncc-finance-mobile.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgJpc_WopHtThpMRMvIBBrY2crQ2KfPz4',
    appId: '1:767296020733:ios:b3c6228a51a20e770fde94',
    messagingSenderId: '767296020733',
    projectId: 'ncc-finance-mobile',
    storageBucket: 'ncc-finance-mobile.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaevHLMDESXiMmY7kpOy0PzTOj-pde_5w',
    appId: '1:767296020733:web:ceeeb06a993aa1e30fde94',
    messagingSenderId: '767296020733',
    projectId: 'ncc-finance-mobile',
    authDomain: 'ncc-finance-mobile.firebaseapp.com',
    storageBucket: 'ncc-finance-mobile.firebasestorage.app',
    measurementId: 'G-BGEBBMGY54',
  );
}
